export {HomePage} from './home/HomePage';
export {AboutUsPage} from './about/AboutUsPage';
export {ContactPage} from './contact/ContactPage';
export {SearchPage} from './search/SearchPage';
export {ProductPage} from './product/ProductPage';
export {CartPage} from './cart/CartPage';
export {CheckOutPage} from './checkout/CheckOutPage';
export {GalleryPage} from './gallery/GalleryPage';
export {FavoritesPage} from './favorites/FavoritesPage';